FROM debian:bookworm

RUN apt-get update && apt-get install -y redis-server

EXPOSE 6379

CMD ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]
# Docker containers need to communicate,that's why we disable protection