services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception  
      
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception


  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - inception

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception

  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "30000-31000:30000-31000"
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always 


volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
