services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception  
      
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception


  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - inception

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception

  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    env_file: .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

#port 21 to connect with ftp in terminal
#ports 21000-21010 are used for file transfer , 11 ports randomly is enough , bcs if we need to open multiple tabs or upload multiple files

  static-website:
    build: requirements/bonus/static-website
    container_name: static-website
    volumes:
      - static-website:/var/www/html
    networks:
      - inception

  backup-db:
    build: requirements/bonus/backup-db
    container_name: backup-db
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:
  static-website:

networks:
  inception:
