# start FTP server (turn it ON)
listen=YES
# no random people , only users with username/password
anonymous_enable=NO
# allow your created user to login
local_enable=YES
# allow upload / delete / edit files
write_enable=YES
# pems of files you upload , (give the perms when testing inside browser), final_permission = default_permission - umask
file_open_mode=0755
local_umask=022
# user stays inside /var/www/html (cannot go outside)
chroot_local_user=YES
# allow writing inside that folder (fix permission issue, by default refuse it , bcs the folder is writable inside dir)
allow_writeable_chroot=YES
# home files we see when logged (WordPress files)
local_root=/var/www/html
# ports used to transfer files (matched with docker compose)
pasv_min_port=21000
pasv_max_port=21010