listen=YES
# start FTP server (turn it ON)
anonymous_enable=NO
# no random people , only users with username/password
local_enable=YES
# allow your created user (rmaanane) to login
write_enable=YES
# allow upload / delete / edit files
file_open_mode=0755
local_umask=022
# pems of files you upload , (give the perms when testing inside browser), final_permission = default_permission - umask
chroot_local_user=YES
# user stays inside /var/www/html (cannot go outside)
allow_writeable_chroot=YES
# allow writing inside that folder (fix permission issue, by default refuse it , bcs the folder is writable inside dir)
local_root=/var/www/html
# home files we see when logged (WordPress files)
pasv_min_port=21000
pasv_max_port=21010
# ports used to transfer files (matched with docker compose)