FROM debian:bookworm

RUN apt-get update && apt-get install -y nginx openssl

# Create folder to store SSL files
RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 \
-newkey rsa:2048 \
-keyout /etc/nginx/ssl/inception.key \
-out /etc/nginx/ssl/inception.crt \
-subj "/C=MA/ST=Marrakesh-Safi/L=Benguerir/O=42/OU=1337/CN=rmaanane.42.fr"

#by default nginx come with this path
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]