events {}

http {
    server {
        listen 443 ssl;
        ssl_protocols TLSv1.2;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        server_name localhost;

        location / {
            # proxy_pass http://wordpress:9000; #proxy pass means nginx receives request from browser then sends it to WordPress container
            return 200 "Rida Maanane\n";
        }
    }
}