server {
    listen 443 ssl;
    server_name rmaanane.42.fr;

    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # need to understand (fastgi and socket and php and fpm and socket file) properly how it works 
    location ~ \.php$ { 
        include fastcgi.conf;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Adminer (https://rmaanane.42.fr/adminer/)
    location /adminer/ {
        proxy_pass http://adminer:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # static-website (https://rmaanane.42.fr/static-website/)
    location /static-website/ {
        proxy_pass http://static-website:69/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}